### ISSUE TITLE
Django-3.1: In to_attribute(), get_language() may return None

### ISSUE THREAD

**Issue by raratiru** [matthiask/django-translated-fields#24]
https://github.com/matthiask/django-translated-fields/blob/3383755b786dd51c2e2314e444cc640136cb3985/translated_fields/fields.py#L43-L45

According to the [docs of `get_language()`](https://docs.djangoproject.com/en/3.1/ref/utils/#django.utils.translation.get_language):

> ...  Returns None if translations are temporarily deactivated

In my code, I am using `to_attribute` in a [`ModelForm`](https://github.com/raratiru/django-letsagree/blob/0bf60b7b91a4b8d0921a41be466d607fc03c261b/letsagree/forms.py#L46-L53):

```python
class PendingConsentForm(forms.ModelForm):
...
    class Meta:
        model = models.Term
        fields = (
            "date_created",
            to_attribute("summary"),
            to_attribute("content"),
            "agree",
        )
```

After upgrading to Django-3.1, when I `./manage.py migrate` in my project, I receive this error:

`django.core.exceptions.FieldError: Unknown field(s) (summary_none, content_none) specified for Term`

This is because `get_language()` returns `None`. 

How could this be solved?

Possible solutions in `def to_attribute(name, language_code=None):`

* `language = get_language() or language_code`
* `language = language_code or get_language() or settings.LANGUAGE_CODE`

**Comment by matthiask** [comment]
Hey

It seems that `to_attribute`  is evaluated when the server starts. I think that the form will contain an arbitrary language's fields instead of the fields for the current language.

You should move the `PendingConsentForm` definition somewhere where it is evaluated again when the current language changes (I think). This should fix the migration problem as a side effect.

**Comment by raratiru** [comment]
The particular problem appeared after updating to Django-3.1, however, I have not found out what changed.

My thought was that `to_attribute` is not useful in the case where Django returns `None` because it will certainly return a non-existent field. This is why I proposed to -at least- return the field of the default language.

Unless I misused it in that case which is to present in the ModelForm certain fields of the Model, not all.

**Comment by raratiru** [comment]
There is no issue with `to_attribute` or `get_language`, they work great.

Something has changed in how and why django imports certain modules.

It seems to be an issue with a chain of imports: `urls.py` -> `views.py` -> `forms.py` as shown in the full error report:

```
Traceback (most recent call last):
  File "./manage.py", line 36, in <module>
    main()
  File "./manage.py", line 32, in main
    execute_from_command_line(sys.argv)
  File "/home/flyer/.virtualenvs/migrd/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/flyer/.virtualenvs/migrd/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/flyer/.virtualenvs/migrd/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/flyer/.virtualenvs/migrd/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/home/flyer/.virtualenvs/migrd/lib/python3.8/site-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/flyer/.virtualenvs/migrd/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 75, in handle
    self.check(databases=[database])
  File "/home/flyer/.virtualenvs/migrd/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = checks.run_checks(
  File "/home/flyer/.virtualenvs/migrd/lib/python3.8/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/flyer/.virtualenvs/migrd/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/flyer/.virtualenvs/migrd/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/flyer/.virtualenvs/migrd/lib/python3.8/site-packages/django/urls/resolvers.py", line 408, in check
    for pattern in self.url_patterns:
  File "/home/flyer/.virtualenvs/migrd/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/flyer/.virtualenvs/migrd/lib/python3.8/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/flyer/.virtualenvs/migrd/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/flyer/.virtualenvs/migrd/lib/python3.8/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/flyer/02/migr/migr/urls.py", line 25, in <module>
    path('path/to/letsagree/', include('letsagree.urls')),
  File "/home/flyer/.virtualenvs/migrd/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/flyer/02/django-letsagree/letsagree/urls.py", line 16, in <module>
    from letsagree.views import PendingView
  File "/home/flyer/02/django-letsagree/letsagree/views.py", line 23, in <module>
    from letsagree.forms import PendingAgreementFormSet
  File "/home/flyer/02/django-letsagree/letsagree/forms.py", line 23, in <module>
    class PendingConsentForm(forms.ModelForm):
  File "/home/flyer/.virtualenvs/migrd/lib/python3.8/site-packages/django/forms/models.py", line 268, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (summary_None, content_None) specified for Term

```

I will dig deeper. Thank you!

**Comment by matthiask** [comment]
Thanks! So as I wrote above it seems to me that `PendingConsentForm` is initialized when the server starts. Which means that when the language changes you still only had the fields from an arbitrary (the first?) language in the form and formset.

Again, this looks very much like a bug in the current (working) code to me.

**Comment by raratiru** [comment]
Thank you! I just filed a [bug report](https://code.djangoproject.com/ticket/31911#ticket).

**Comment by raratiru** [comment]
Just an update in case you would like to comment on the [pending decision](https://code.djangoproject.com/ticket/31911#ticket) to be made.

[Carlton Gibson](https://code.djangoproject.com/ticket/31911#comment:1):

> So we need to decide what to say...
> 
> I'm inclined to think that using get_language() at import time (during start-up) shouldn't be supported, since we're not in an active language context, but happy to take guidance on that. 

As a user, when I set `USE_I18N = True`, I would expect `get_language()` to return `LANGUAGE_CODE` instead of `None`.

**Comment by matthiask** [comment]
Thank you!

I just read the discussion on the ticket and I also think running `modelform_factory` within a context where a language is set is the way to go. (That is, inside the request-response cycle.)
